
public class ExceptionEx9 {

	public static void main(String[] args) {

		try {
			Exception e = new Exception("고의로 발생 시켰습니다.");
			throw e; // 예외를 발생 시킴
//			throw new Exception("고의로 발생 시켰습니다."); // 위에 두줄을 한줄로 쓸 수 있다
		} catch (Exception e) {
			System.out.println("에러 메세지 : " + e.getMessage());
			e.printStackTrace();
		}
		System.out.println("프로그램이 정상 종료되었습니다.");
	}

}
